name: 'nyc_taxi_dbt'
version: '1.0.0'
config-version: 2
profile: 'nyc_taxi'
model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
vars:
  start_date: '2013-01-01'
models:
  nyc_taxi_dbt:
    staging:
      +materialized: view
      +schema: bronze
    intermediate:
      +materialized: view
      +schema: silver
    marts:
      core:
        +materialized: table
        +schema: gold
      aggregations:
        +materialized: table
        +schema: gold
      insights:
        +materialized: table
        +schema: insights
