name: 'nyc_taxi_dbt'
version: '1.0.0'
config-version: 2

profile: 'nyc_taxi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

require-dbt-version: ">=1.5.0"

models:
  nyc_taxi_dbt:
    staging:
      +materialized: view
      +schema: bronze
    intermediate:
      +materialized: table
      +schema: silver
    marts:
      core:
        +materialized: table
        +schema: gold
      aggregations:
        +materialized: table
        +schema: gold
      insights:
        +materialized: view    
        +schema: insights